### PR TITLE
Add pinsLabkey

### PR DESCRIPTION
**Pull request by camorosi**

### CODE REVIEW

**Review by bkutlu — COMMENTED** [review]
Should the dpbuild, dpi versions be (>=0.02)?
Please add issue references in the NEWS.md.

**Comment by camorosi** [comment]
> Should the dpbuild, dpi versions be (>=0.02)?

I was keeping the dpbuild and dpi version requirements within daapr, since the intended usage is to install dpdeploy, dpdbuild, and dpi via daapr. But it may be helpful to have the version requirements in both places

**Comment by amashadihossein** [comment]
> > Should the dpbuild, dpi versions be (>=0.02)?
> 
> I was keeping the dpbuild and dpi version requirements within daapr, since the intended usage is to install dpdeploy, dpdbuild, and dpi via daapr. But it may be helpful to have the version requirements in both places

Interesting point re version req management within components of `daapr`! I could see possibly someone starting w/ install via `daapr`, but then at some point updating, let's say just `dpdeploy` by itself, so in that case, it'd be good to have within `DESCRIPTION` of `dpdeploy` the min version reqs for it to functioning properly specified.
 
Taking a look at `tidyverse`, as a mature example, and the pkgs it installs, I think what I see is that specific version requirements of dependencies for any given pkg, e.g., `readr` is handled within its `DESCRIPTION`, but then within `DESCRIPTION` of `tidyverse`, there is a tighter specification (I am assuming to ensure all components included in the install bundle play nice together). Does that sound reasonable as a pattern to follow?

**Review by amashadihossein — APPROVED** [review]

**Comment by camorosi** [comment]
@amashadihossein sounds reasonable --  I'll add version requirements to `dpbuild` and `dpdeploy`

**Pull request merged**
