### PR TITLE
adjust code of conduct

### PR DESCRIPTION
**Pull request by geauxdojang**
It looks like that the code of conduct is very standard for most of the projects and often adapted from [Contributor Covenant](https://www.contributor-covenant.org/version/2/0/code_of_conduct.html). I mainly adjusted it to daapr. Let me know if we need a substantial text change. Thanks.

### CODE REVIEW

**Comment by geauxdojang** [comment]
@amashadihossein @camorosi Can you please review the changes in the PR (code of conduct and correcting some typos)? Thank you.

**Review by camorosi — COMMENTED** [review]
Content looks good. 

Will we be adding this code of conduct to the other packages? Or perhaps we should only have the code of conduct on daapr so we don't have to maintain four separate codes of conduct since this is somewhat customized from the original source?

**Comment by geauxdojang** [comment]
> Content looks good.
> 
> Will we be adding this code of conduct to the other packages? Or perhaps we should only have the code of conduct on daapr so we don't have to maintain four separate codes of conduct since this is somewhat customized from the original source?

I was also wondering about this conduct of conduct being in `dpdeploy` instead of `daapr`.

**Review by amashadihossein — APPROVED** [review]
Looks great!

**Pull request merged**
